### PR TITLE
Add div props to TypeScript interface

### PR DESCRIPTION
**Pull request by mlbonniec**
Hi :)

Here is a PR to fix the issue #69.

I extended the `MarkdownViewProps` interface with `HTMLAttributes<HTMLDivElement>`, omitting the `dangerouslySetInnerHTML`, so it can be a boolean, instead of a string.

Hope you'll accept this PR :wink:

### CODE REVIEW

**Comment by jerolimov** [comment]
Hi @mlbonniec, yes I like it. :+1:

But can you please drop the package-lock.json and revert the changes in yarn.lock.

Thanks :)

**Comment by mlbonniec** [comment]
> Hi @mlbonniec, yes I like it. 👍
> 
> But can you please drop the package-lock.json and revert the changes in yarn.lock.
> 
> Thanks :)

Done ✅

**Comment by jerolimov** [comment]
Thanks @mlbonniec :)

**Comment by mlbonniec** [comment]
Thanks to you @jerolimov :wink:

And don't forget to publish it to npm :)

**Comment by jerolimov** [comment]
A new version is successfully published (react-showdown@2.3.1)

**Pull request merged**
